---
title: "Datawrangling_i"
output: github_document
---
```{r setup}
library (tidyverse)
library (readxl)
library(haven)
```

##read in some data

Read in the litters dataset.

```{r}
litters_df= read_csv("./data/FAS_litters.csv")
litters_df=janitor::clean_names(litters_df)
```

## Take a look at the data

Printing in the console

```{r}
litters_df
```
```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```


##options to read csv

check out `read_csv()` for more information

## other file formats

Read in an excel file

```{r}
library(readxl)
mlb_df= read_excel("./data/mlb11.xlsx", range="A1:F7")
mlb_df
```

Read in a SAS file
```{r}
pulse_df=read_sas("./data/public_pulse_data.sas7bdat")
```

## Comparison with Base R

what about `read.csv`....?

```{r}
litters_base=read.csv("data/FAS_litters.csv")
litters_readr=read_csv("data/FAS_litters.csv")

litters_base
litters_readr
```
## Exporting data 

Export the mlb sub-table.

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```


