---
title: "data_manipulation"
output: github_document
---



```{r setup}
library (tidyverse)
```

Load in the FAS Litters

```{r}
litters_df=read_csv("./data/FAS_litters.csv")
litters_df=janitor::clean_names(litters_df)
```
## `select`

Choose some columns and not others.

```{r}
select(litters_df, group,gd0_weight)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```
```{r}
select(litters_df, -litter_number)
```
Renaming columns

```{r}
select(litters_df, GROUP=group, LiTTer_NUmBer=litter_number)
```
```{r}
rename(litters_df, GROUP=group, LiTTer_NUmBer=litter_number)
```

Select helpers

```{r}
select (litters_df, starts_with("gd"))
```
```{r}
select(litters_df, litter_number, everything())
```
```{r}
relocate(litters_df, litter_number)
```
## `filter`

```{r}
filter(litters_df, gd0_weight <22)
```

```{r}
filter(litters_df, gd0_weight >=22)
```

```{r}
filter(litters_df, gd_of_birth==20)
```
```{r}
filter(litters_df, !(gd_of_birth==20))
```
```{r}
filter(litters_df, gd_of_birth !=20)
```
```{r}
filter (litters_df, gd0_weight >=22, gd_of_birth==20)
```
```{r}
filter(litters_df, group=="Mod8")
```

```{r}
filter(litters_df, group %in% c("Mod8", "Con7") )
```
## `mutate`

create new variable, modifying cariables

```{r}
mutate(
  litters_df, 
      wt_gain=gd18_weight-gd0_weight,
      group=str_to_lower(group))
```
## `arange`

```{r}

arrange(litters_df, pups_born_alive)
```
## %>%

```{r}
litters_data_raw=read_csv("./data/FAS_litters.csv")
litters_clean_name= janitor::clean_names (litters_data_raw)
litters_data_selected=select(litters_clean_name, -pups_survive)
litters_mutated=mutate(litters_data_selected, wt_gain=gd18_weight-gd0_weight)
litters_without_missing= drop_na(litters_mutated, gd0_weight)
```

USE THE PIPE OPERATOR INSTEAD

hotkeys= shift command m
```{r}
litters_df =
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain=gd18_weight-gd0_weight) %>% 
  drop_na(gd0_weight)
  ```

